name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-tests:
    strategy:
      matrix:
        go-version: ["1.19", "1.20"]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Tools
      run: make install-tools
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Run sample
      run: go run -race ./sample/...
